/**
 * Where the survey API is, and every label and colour this feature uses.
 *
 * Same rule the assistant follows: nothing else in this directory knows a URL
 * or hard-codes a word the operator reads. Change it here and the whole page
 * follows.
 */

const fromEnv = import.meta.env.VITE_API_BASE_URL

export const surveyConfig = {
  /** Base URL of the FastAPI backend. Override with VITE_API_BASE_URL. */
  apiBaseUrl: (fromEnv && fromEnv.trim()) || "http://127.0.0.1:8000",

  endpoints: {
    surveys: "/survey",
    export: (id) => `/survey/${encodeURIComponent(id)}/export`,
    map: (id) => `/survey/${encodeURIComponent(id)}/map`,
    actions: (id) => `/survey/${encodeURIComponent(id)}/actions.csv`,
  },
}

/**
 * Severity tiers, mapped onto the dashboard's existing palette variables.
 *
 * The engine decides which tier a thing is in and this only decides how it
 * looks, exactly as the backend's own severity table is looked up rather than
 * inferred. A tier the engine adds later that is not listed here renders in
 * the neutral fallback instead of guessing a colour, because picking a colour
 * for an unknown risk level is itself a claim.
 */
export const tierStyle = {
  critical: { label: "Critical", color: "var(--danger)", tint: "#fdeaea" },
  medium: { label: "Medium", color: "var(--warning)", tint: "#fdf3e7" },
  low: { label: "Low", color: "var(--success)", tint: "#eaf6ef" },
}

export const tierFallback = { label: "Unclassified", color: "var(--muted)", tint: "#eef2f6" }

export function styleForTier(tier) {
  return tierStyle[tier] || tierFallback
}

/** Priority filter options. Derived from nothing; they are plain cut-offs. */
export const priorityOptions = [
  { value: "all", label: "All" },
  { value: "5", label: "Top 5" },
  { value: "10", label: "Top 10" },
  { value: "20", label: "Top 20" },
]

export const copy = {
  title: "Survey Hazard Intelligence",
  subtitle: "Where the hazards are, and which one to look at first",
  relativeMode: "Relative survey coordinates",
  relativeNote:
    "This survey has no navigation. Positions are pixel offsets inside the sonar " +
    "strip, not geographic coordinates. Nothing on this page is a GPS position.",
  geoMode: "Geo-referenced",
  geoNote:
    "Positions are interpolated from the survey's navigation. Relative pixel " +
    "coordinates are kept alongside them.",
  demoBanner: "Synthetic demo data",
  demoNote:
    "Every contact in this survey was generated by the demo script. No sonar was " +
    "recorded and nothing here is evidence of anything.",
  noSurveys:
    "No processed surveys yet. Run run_survey.py or demo_survey.py and the " +
    "results appear here.",
  noHotspots:
    "The detector returned nothing above the confidence threshold for this " +
    "survey. It ran; there is simply nothing to rank.",
  noMatch: "No hotspot matches these filters.",
  askAssistant: "Ask the assistant about this hazard",
  disclaimer:
    "Severity weights and recommended actions are a configurable heuristic " +
    "chosen for this project. They are not Navy, Coast Guard, NOAA or IMO " +
    "procedure and carry no authority.",
}
